In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("urbankart_sales_clean.csv")

In [3]:
df.head(10)

,order_id,order_date,region,city,product_name,category,quantity,unit_price,total_revenue,customer_id,sales_channel
0,UK-2026-103168,2026-05-10,East,Patna,Matte Lipstick Set,Beauty,2,933,1866,CUST-68709,Marketplace
1,UK-2026-103684,2026-05-07,South,Chennai,Vitamin C Serum,Beauty,1,682,682,CUST-75684,App
2,UK-2026-104082,2026-06-21,South,Bengaluru,Wireless Earbuds Pro,Electronics,1,3107,3107,CUST-85468,Marketplace
3,UK-2026-101291,2026-02-18,South,Hyderabad,Electric Kettle 1.5L,Home & Kitchen,1,1122,1122,CUST-36533,App
4,UK-2026-101181,2026-02-18,Central,Raipur,Denim Jacket,Fashion,1,2196,2196,CUST-95981,Website
5,UK-2026-102178,2026-03-23,West,Mumbai,Electric Kettle 1.5L,Home & Kitchen,1,1126,1126,CUST-35368,Website
6,UK-2026-102705,2026-04-21,South,Hyderabad,Bluetooth Speaker Mini,Electronics,2,1541,3082,CUST-97692,Marketplace
7,UK-2026-102120,2026-03-05,North,Delhi,43-inch Smart TV,Electronics,1,26675,26675,CUST-45342,Marketplace
8,UK-2026-104889,2026-06-13,North,Chandigarh,Noise-Cancelling Headphones,Electronics,1,9405,9405,CUST-35466,App
9,UK-2026-102577,2026-04-21,North,Delhi,Ethnic Dupatta,Fashion,2,518,1036,CUST-94200,App

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4820 entries, 0 to 4819
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       4820 non-null   object
 1   order_date     4820 non-null   object
 2   region         4820 non-null   object
 3   city           4786 non-null   object
 4   product_name   4820 non-null   object
 5   category       4820 non-null   object
 6   quantity       4820 non-null   int64
 7   unit_price     4820 non-null   int64
 8   total_revenue  4820 non-null   int64
 9   customer_id    4820 non-null   object
 10  sales_channel  4820 non-null   object
dtypes: int64(3), object(8)
memory usage: 414.3+ KB

In [5]:
df.shape

(4820, 11)

In [6]:
df['order_date'].head(10)

0    2026-05-10
1    2026-05-07
2    2026-06-21
3    2026-02-18
4    2026-02-18
5    2026-03-23
6    2026-04-21
7    2026-03-05
8    2026-06-13
9    2026-04-21
Name: order_date, dtype: object

In [16]:
# Q --> 1. Top Region

In [8]:
df['region'].unique()

array(['East', 'South', 'Central', 'West', 'North'], dtype=object)

In [9]:
df['region'].value_counts()

region
South      1424
North      1158
West       1049
East        662
Central     527
Name: count, dtype: int64

In [12]:
df.groupby("region")['total_revenue'].sum()

region
Central     3785835
East        5472100
North       9551220
South      12373492
West        8717641
Name: total_revenue, dtype: int64

In [14]:
region_revenue=df.groupby("region")['total_revenue'].sum()
region_revenue.idxmax()

'South'

In [15]:
region_revenue.max()

12373492

In [17]:
# Q --> 2. Revenue momentum

In [18]:
df['order_date'].dtype

dtype('O')

In [19]:
df['order_date']=pd.to_datetime(df['order_date'])

In [20]:
df['order_date'].dtype

dtype('<M8[ns]')

In [21]:
df['month']=df['order_date'].dt.month

In [22]:
df['month'].head(10)

0    5
1    5
2    6
3    2
4    2
5    3
6    4
7    3
8    6
9    4
Name: month, dtype: int32

In [23]:
monthly_revenue=df.groupby('month')['total_revenue'].sum()

In [24]:
monthly_revenue

month
1    5317204
2    5257298
3    5771539
4    7170810
5    7979620
6    8403817
Name: total_revenue, dtype: int64

In [25]:
april_to_may=((monthly_revenue[5]-monthly_revenue[4])/monthly_revenue[4])*100

In [26]:
april_to_may

np.float64(11.279199978802952)

In [27]:
may_to_june=((monthly_revenue[6]-monthly_revenue[5])/monthly_revenue[5])*100

In [28]:
may_to_june

np.float64(5.316005022795571)

In [30]:
round(april_to_may,1)

np.float64(11.3)

In [31]:
round(may_to_june,1)

np.float64(5.3)

In [32]:
# Q --> 3. The channel decision

In [33]:
channel_revenue=df.groupby('sales_channel')['total_revenue'].sum()

In [34]:
channel_revenue

sales_channel
App            16832676
Marketplace    10987036
Website        12080576
Name: total_revenue, dtype: int64

In [35]:
channel_revenue.sum()

np.int64(39900288)

In [36]:
marketplace_share=(channel_revenue['Marketplace']/channel_revenue.sum())*100

In [37]:
round(marketplace_share,1)

np.float64(27.5)

In [40]:
channel_orders=df['sales_channel'].value_counts()

In [41]:
channel_orders

sales_channel
App            2227
Website        1594
Marketplace     999
Name: count, dtype: int64

In [42]:
aov=channel_revenue/channel_orders  # aov = average order value

In [43]:
aov

sales_channel
App             7558.453525
Marketplace    10998.034034
Website         7578.780427
dtype: float64

In [44]:
round(aov,2)

sales_channel
App             7558.45
Marketplace    10998.03
Website         7578.78
dtype: float64

In [45]:
channel_monthly = df.groupby(["month", "sales_channel"])["total_revenue"].sum()

In [46]:
channel_monthly

month  sales_channel
1      App              2336518
       Marketplace      1100817
       Website          1879869
2      App              2357000
       Marketplace      1139801
       Website          1760497
3      App              2611309
       Marketplace      1426756
       Website          1733474
4      App              3075089
       Marketplace      2116538
       Website          1979183
5      App              3357172
       Marketplace      2145145
       Website          2477303
6      App              3095588
       Marketplace      3057979
       Website          2250250
Name: total_revenue, dtype: int64

In [47]:
channel_monthly.unstack()

sales_channel      App  Marketplace  Website
month
1              2336518      1100817  1879869
2              2357000      1139801  1760497
3              2611309      1426756  1733474
4              3075089      2116538  1979183
5              3357172      2145145  2477303
6              3095588      3057979  2250250

In [48]:
channel_growth=channel_monthly.unstack().pct_change()*100

In [49]:
round(channel_growth,1)

sales_channel   App  Marketplace  Website
month
1               NaN          NaN      NaN
2               0.9          3.5     -6.4
3              10.8         25.2     -1.5
4              17.8         48.3     14.2
5               9.2          1.4     25.2
6              -7.8         42.6     -9.2

In [50]:
df["expected_revenue"] = df["quantity"] * df["unit_price"]

invalid_rows = df[df["expected_revenue"] != df["total_revenue"]]

len(invalid_rows)

0